
# This file is automatically generated, you probably don't want to edit this

cartoOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cartoOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            individus = NULL,
            coox = NULL,
            cooy = NULL,
            hedo = NULL,
            regtype = "1",
            colabove = 0,
            colbelow = 7.5, ...) {

            super$initialize(
                package="SEDA",
                name="carto",
                requiresData=TRUE,
                ...)

            private$..individus <- jmvcore::OptionVariable$new(
                "individus",
                individus,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..coox <- jmvcore::OptionVariable$new(
                "coox",
                coox,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..cooy <- jmvcore::OptionVariable$new(
                "cooy",
                cooy,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..hedo <- jmvcore::OptionVariables$new(
                "hedo",
                hedo,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..regtype <- jmvcore::OptionList$new(
                "regtype",
                regtype,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4"),
                default="1")
            private$..colabove <- jmvcore::OptionNumber$new(
                "colabove",
                colabove,
                default=0)
            private$..colbelow <- jmvcore::OptionNumber$new(
                "colbelow",
                colbelow,
                default=7.5)

            self$.addOption(private$..individus)
            self$.addOption(private$..coox)
            self$.addOption(private$..cooy)
            self$.addOption(private$..hedo)
            self$.addOption(private$..regtype)
            self$.addOption(private$..colabove)
            self$.addOption(private$..colbelow)
        }),
    active = list(
        individus = function() private$..individus$value,
        coox = function() private$..coox$value,
        cooy = function() private$..cooy$value,
        hedo = function() private$..hedo$value,
        regtype = function() private$..regtype$value,
        colabove = function() private$..colabove$value,
        colbelow = function() private$..colbelow$value),
    private = list(
        ..individus = NA,
        ..coox = NA,
        ..cooy = NA,
        ..hedo = NA,
        ..regtype = NA,
        ..colabove = NA,
        ..colbelow = NA)
)

cartoResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cartoResults",
    inherit = jmvcore::Group,
    active = list(
        plotcarto = function() private$.items[["plotcarto"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="External Preference Mapping")
            self$add(jmvcore::Image$new(
                options=options,
                name="plotcarto",
                title="Representation of the Products",
                width=600,
                height=500,
                renderFun=".plotcartograph"))}))

cartoBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cartoBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "carto",
                version = c(1,0,0),
                options = options,
                results = cartoResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' External Preference Mapping
#'
#' 
#' @param data .
#' @param individus .
#' @param coox .
#' @param cooy .
#' @param hedo .
#' @param regtype .
#' @param colabove .
#' @param colbelow .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plotcarto} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
carto <- function(
    data,
    individus,
    coox,
    cooy,
    hedo,
    regtype = "1",
    colabove = 0,
    colbelow = 7.5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("carto requires jmvcore to be installed (restart may be required)")

    if ( ! missing(individus)) individus <- jmvcore::resolveQuo(jmvcore::enquo(individus))
    if ( ! missing(coox)) coox <- jmvcore::resolveQuo(jmvcore::enquo(coox))
    if ( ! missing(cooy)) cooy <- jmvcore::resolveQuo(jmvcore::enquo(cooy))
    if ( ! missing(hedo)) hedo <- jmvcore::resolveQuo(jmvcore::enquo(hedo))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(individus), individus, NULL),
            `if`( ! missing(coox), coox, NULL),
            `if`( ! missing(cooy), cooy, NULL),
            `if`( ! missing(hedo), hedo, NULL))

    for (v in individus) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- cartoOptions$new(
        individus = individus,
        coox = coox,
        cooy = cooy,
        hedo = hedo,
        regtype = regtype,
        colabove = colabove,
        colbelow = colbelow)

    analysis <- cartoClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

