
# This file is automatically generated, you probably don't want to edit this

cataOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cataOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            stimuli = NULL,
            group = NULL,
            tuto = TRUE,
            thres = 5, ...) {

            super$initialize(
                package="SEDA",
                name="cata",
                requiresData=TRUE,
                ...)

            private$..stimuli <- jmvcore::OptionVariable$new(
                "stimuli",
                stimuli,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariables$new(
                "group",
                group,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..tuto <- jmvcore::OptionBool$new(
                "tuto",
                tuto,
                default=TRUE)
            private$..thres <- jmvcore::OptionNumber$new(
                "thres",
                thres,
                default=5)

            self$.addOption(private$..stimuli)
            self$.addOption(private$..group)
            self$.addOption(private$..tuto)
            self$.addOption(private$..thres)
        }),
    active = list(
        stimuli = function() private$..stimuli$value,
        group = function() private$..group$value,
        tuto = function() private$..tuto$value,
        thres = function() private$..thres$value),
    private = list(
        ..stimuli = NA,
        ..group = NA,
        ..tuto = NA,
        ..thres = NA)
)

cataResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cataResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        textualgroup = function() private$.items[["textualgroup"]],
        dfresgroup = function() private$.items[["dfresgroup"]],
        plotcata = function() private$.items[["plotcata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of CATA data",
                refs=list(
                    "cata",
                    "sensominer",
                    "senso"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible="(tuto)"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    textual = function() private$.items[["textual"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="textualgroup",
                            title="Stimuli by CATA Data Table")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="textual",
                            title="Contingency Table",
                            visible="stimuli",
                            clearWith=list(
                                "stimuli",
                                "group"),
                            columns=list()))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    dfres = function() private$.items[["dfres"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="dfresgroup",
                            title="Description of the Stimuli According to CATA")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="dfres",
                            title="Description of the Stimuli According to CATA",
                            visible="stimuli",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="word", 
                                    `title`="CATA", 
                                    `type`="text"),
                                list(
                                    `name`="internper", 
                                    `title`="Intern %", 
                                    `type`="Number"),
                                list(
                                    `name`="globper", 
                                    `title`="Global %", 
                                    `type`="Number"),
                                list(
                                    `name`="internfreq", 
                                    `title`="Intern frequency", 
                                    `type`="Number"),
                                list(
                                    `name`="globfreq", 
                                    `title`="Global frequency", 
                                    `type`="Number"),
                                list(
                                    `name`="pvaluedfres", 
                                    `title`="p", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="vtest", 
                                    `title`="Vtest", 
                                    `type`="Number"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotcata",
                title="Representation of the Stimuli and the CATA",
                width=600,
                height=500,
                renderFun=".plotcatatis"))}))

cataBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cataBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "cata",
                version = c(1,0,0),
                options = options,
                results = cataResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Analysis of CATA data
#'
#' 
#' @param data .
#' @param stimuli .
#' @param group .
#' @param tuto .
#' @param thres .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$textualgroup$textual} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dfresgroup$dfres} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotcata} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
cata <- function(
    data,
    stimuli,
    group,
    tuto = TRUE,
    thres = 5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cata requires jmvcore to be installed (restart may be required)")

    if ( ! missing(stimuli)) stimuli <- jmvcore::resolveQuo(jmvcore::enquo(stimuli))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(stimuli), stimuli, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in stimuli) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- cataOptions$new(
        stimuli = stimuli,
        group = group,
        tuto = tuto,
        thres = thres)

    analysis <- cataClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

