
# This file is automatically generated, you probably don't want to edit this

NappingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NappingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            actvars = NULL,
            individus = NULL,
            qualisup = NULL,
            tuto = TRUE,
            showCode = FALSE,
            nFactors = 2,
            proba = 5,
            abs = 1,
            ord = 2,
            ncp = 5,
            graphclassif = FALSE,
            nbclust = -1, ...) {

            super$initialize(
                package="SEDA",
                name="Napping",
                requiresData=TRUE,
                ...)

            private$..actvars <- jmvcore::OptionVariables$new(
                "actvars",
                actvars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..individus <- jmvcore::OptionVariable$new(
                "individus",
                individus,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..qualisup <- jmvcore::OptionVariables$new(
                "qualisup",
                qualisup,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..tuto <- jmvcore::OptionBool$new(
                "tuto",
                tuto,
                default=TRUE)
            private$..showCode <- jmvcore::OptionBool$new(
                "showCode",
                showCode,
                default=FALSE)
            private$..nFactors <- jmvcore::OptionInteger$new(
                "nFactors",
                nFactors,
                default=2)
            private$..proba <- jmvcore::OptionNumber$new(
                "proba",
                proba,
                default=5)
            private$..abs <- jmvcore::OptionInteger$new(
                "abs",
                abs,
                default=1)
            private$..ord <- jmvcore::OptionInteger$new(
                "ord",
                ord,
                default=2)
            private$..ncp <- jmvcore::OptionInteger$new(
                "ncp",
                ncp,
                default=5)
            private$..newvar <- jmvcore::OptionOutput$new(
                "newvar")
            private$..graphclassif <- jmvcore::OptionBool$new(
                "graphclassif",
                graphclassif,
                default=FALSE)
            private$..nbclust <- jmvcore::OptionInteger$new(
                "nbclust",
                nbclust,
                default=-1)
            private$..newvar2 <- jmvcore::OptionOutput$new(
                "newvar2")

            self$.addOption(private$..actvars)
            self$.addOption(private$..individus)
            self$.addOption(private$..qualisup)
            self$.addOption(private$..tuto)
            self$.addOption(private$..showCode)
            self$.addOption(private$..nFactors)
            self$.addOption(private$..proba)
            self$.addOption(private$..abs)
            self$.addOption(private$..ord)
            self$.addOption(private$..ncp)
            self$.addOption(private$..newvar)
            self$.addOption(private$..graphclassif)
            self$.addOption(private$..nbclust)
            self$.addOption(private$..newvar2)
        }),
    active = list(
        actvars = function() private$..actvars$value,
        individus = function() private$..individus$value,
        qualisup = function() private$..qualisup$value,
        tuto = function() private$..tuto$value,
        showCode = function() private$..showCode$value,
        nFactors = function() private$..nFactors$value,
        proba = function() private$..proba$value,
        abs = function() private$..abs$value,
        ord = function() private$..ord$value,
        ncp = function() private$..ncp$value,
        newvar = function() private$..newvar$value,
        graphclassif = function() private$..graphclassif$value,
        nbclust = function() private$..nbclust$value,
        newvar2 = function() private$..newvar2$value),
    private = list(
        ..actvars = NA,
        ..individus = NA,
        ..qualisup = NA,
        ..tuto = NA,
        ..showCode = NA,
        ..nFactors = NA,
        ..proba = NA,
        ..abs = NA,
        ..ord = NA,
        ..ncp = NA,
        ..newvar = NA,
        ..graphclassif = NA,
        ..nbclust = NA,
        ..newvar2 = NA)
)

NappingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NappingResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        step1Guide = function() private$.items[["step1Guide"]],
        eigengroup = function() private$.items[["eigengroup"]],
        plotind = function() private$.items[["plotind"]],
        step2Guide = function() private$.items[["step2Guide"]],
        plotgroup = function() private$.items[["plotgroup"]],
        descdesdim = function() private$.items[["descdesdim"]],
        step3Guide = function() private$.items[["step3Guide"]],
        plotclassif = function() private$.items[["plotclassif"]],
        newvar = function() private$.items[["newvar"]],
        newvar2 = function() private$.items[["newvar2"]],
        code = function() private$.items[["code"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of Napping Data",
                refs=list(
                    "napping",
                    "sensominer",
                    "mfa",
                    "senso"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible="(tuto)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="step1Guide",
                title=""))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eigen = function() private$.items[["eigen"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="eigengroup",
                            title="Eigenvalue Decomposition",
                            clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ncp",
                    "nFactors",
                    "abs",
                    "ord"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eigen",
                            title="Eigenvalue and (Cumulative) Percentage of Variance",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="eigenvalue", 
                                    `title`="Eigenvalue", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="purcent", 
                                    `title`="% of the variance", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="purcentcum", 
                                    `title`="Cumulative %", 
                                    `type`="Number", 
                                    `format`="zto"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotind",
                title="Representation of the Stimuli",
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "abs",
                    "ord",
                    "ncp",
                    "nFactors"),
                width=800,
                height=600,
                renderFun=".plotindividus"))
            self$add(jmvcore::Html$new(
                options=options,
                name="step2Guide",
                title=""))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotgroup",
                title="Representation of the Subjects",
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "abs",
                    "ord",
                    "ncp",
                    "nFactors"),
                width=600,
                height=600,
                renderFun=".plotgroups"))
            self$add(jmvcore::Table$new(
                options=options,
                name="descdesdim",
                title="Automatic Description of the Dimensions",
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "nFactors",
                    "proba"),
                columns=list(
                    list(
                        `name`="dimension", 
                        `title`="Dimension", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="variable", 
                        `title`="Coordinate", 
                        `type`="text"),
                    list(
                        `name`="correlation", 
                        `title`="Correlation", 
                        `type`="Number", 
                        `format`="zto"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="Number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="Integer"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="step3Guide",
                title="",
                visible="(graphclassif)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotclassif",
                title="Representation of the Stimuli According to Clusters",
                visible="(graphclassif)",
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "abs",
                    "ord",
                    "ncp",
                    "nbclust",
                    "graphclassif"),
                width=800,
                height=600,
                renderFun=".plotclassif"))
            self$add(jmvcore::Output$new(
                options=options,
                name="newvar",
                title="Coordinates",
                measureType="continuous",
                initInRun=TRUE,
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ncp")))
            self$add(jmvcore::Output$new(
                options=options,
                name="newvar2",
                title="Cluster",
                measureType="nominal",
                initInRun=TRUE,
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ncp",
                    "nbclust")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="code",
                title="R Code",
                visible="(showCode)",
                clearWith=list(
                    "showCode",
                    "actvars",
                    "qualisup",
                    "individus",
                    "abs",
                    "ord",
                    "nFactors",
                    "proba",
                    "ncp",
                    "graphclassif",
                    "nbclust")))}))

NappingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NappingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "Napping",
                version = c(1,1,0),
                options = options,
                results = NappingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Analysis of Napping Data
#'
#' 
#' @param data .
#' @param actvars .
#' @param individus .
#' @param qualisup .
#' @param tuto .
#' @param showCode .
#' @param nFactors .
#' @param proba .
#' @param abs .
#' @param ord .
#' @param ncp .
#' @param graphclassif .
#' @param nbclust .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$step1Guide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$eigengroup$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotind} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$step2Guide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotgroup} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$descdesdim} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$step3Guide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotclassif} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$newvar} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$newvar2} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$code} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$descdesdim$asDF}
#'
#' \code{as.data.frame(results$descdesdim)}
#'
#' @export
Napping <- function(
    data,
    actvars,
    individus,
    qualisup,
    tuto = TRUE,
    showCode = FALSE,
    nFactors = 2,
    proba = 5,
    abs = 1,
    ord = 2,
    ncp = 5,
    graphclassif = FALSE,
    nbclust = -1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Napping requires jmvcore to be installed (restart may be required)")

    if ( ! missing(actvars)) actvars <- jmvcore::resolveQuo(jmvcore::enquo(actvars))
    if ( ! missing(individus)) individus <- jmvcore::resolveQuo(jmvcore::enquo(individus))
    if ( ! missing(qualisup)) qualisup <- jmvcore::resolveQuo(jmvcore::enquo(qualisup))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(actvars), actvars, NULL),
            `if`( ! missing(individus), individus, NULL),
            `if`( ! missing(qualisup), qualisup, NULL))

    for (v in individus) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- NappingOptions$new(
        actvars = actvars,
        individus = individus,
        qualisup = qualisup,
        tuto = tuto,
        showCode = showCode,
        nFactors = nFactors,
        proba = proba,
        abs = abs,
        ord = ord,
        ncp = ncp,
        graphclassif = graphclassif,
        nbclust = nbclust)

    analysis <- NappingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

