
# This file is automatically generated, you probably don't want to edit this

QDAOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "QDAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            prodeff = NULL,
            paneff = NULL,
            sensoatt = NULL,
            threshold = 0.05, ...) {

            super$initialize(
                package='SEDA',
                name='QDA',
                requiresData=TRUE,
                ...)

            private$..prodeff <- jmvcore::OptionVariable$new(
                "prodeff",
                prodeff)
            private$..paneff <- jmvcore::OptionVariable$new(
                "paneff",
                paneff)
            private$..sensoatt <- jmvcore::OptionVariables$new(
                "sensoatt",
                sensoatt)
            private$..threshold <- jmvcore::OptionNumber$new(
                "threshold",
                threshold,
                default=0.05)

            self$.addOption(private$..prodeff)
            self$.addOption(private$..paneff)
            self$.addOption(private$..sensoatt)
            self$.addOption(private$..threshold)
        }),
    active = list(
        prodeff = function() private$..prodeff$value,
        paneff = function() private$..paneff$value,
        sensoatt = function() private$..sensoatt$value,
        threshold = function() private$..threshold$value),
    private = list(
        ..prodeff = NA,
        ..paneff = NA,
        ..sensoatt = NA,
        ..threshold = NA)
)

QDAResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        resTgroup = function() private$.items[["resTgroup"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of QDA data")
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    resT = function() private$.items[["resT"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="resTgroup",
                            title="Coefficient, p-value and Vtest for each significant attribute")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="resT",
                            title="Sensory Analysis",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="var", 
                                    `title`="Descriptor", 
                                    `type`="text"),
                                list(
                                    `name`="coeff", 
                                    `title`="Coefficient", 
                                    `type`="number"),
                                list(
                                    `name`="adjmean", 
                                    `title`="Adjusted mean", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p-value", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="vtest", 
                                    `title`="Vtest", 
                                    `type`="number"))))}))$new(options=options))}))

QDABase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "QDABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'SEDA',
                name = 'QDA',
                version = c(1,0,0),
                options = options,
                results = QDAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Analysis of QDA data
#'
#' 
#' @param data .
#' @param prodeff .
#' @param paneff .
#' @param sensoatt .
#' @param threshold .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$resTgroup$resT} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
QDA <- function(
    data,
    prodeff,
    paneff,
    sensoatt,
    threshold = 0.05) {

    if ( ! requireNamespace('jmvcore'))
        stop('QDA requires jmvcore to be installed (restart may be required)')

    if ( ! missing(prodeff)) prodeff <- jmvcore::resolveQuo(jmvcore::enquo(prodeff))
    if ( ! missing(paneff)) paneff <- jmvcore::resolveQuo(jmvcore::enquo(paneff))
    if ( ! missing(sensoatt)) sensoatt <- jmvcore::resolveQuo(jmvcore::enquo(sensoatt))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(prodeff), prodeff, NULL),
            `if`( ! missing(paneff), paneff, NULL),
            `if`( ! missing(sensoatt), sensoatt, NULL))


    options <- QDAOptions$new(
        prodeff = prodeff,
        paneff = paneff,
        sensoatt = sensoatt,
        threshold = threshold)

    analysis <- QDAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
