
# This file is automatically generated, you probably don't want to edit this

QDABOOTOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "QDABOOTOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            prod = NULL,
            pane = NULL,
            senso = NULL,
            thresh = 0.05,
            nbsimul = 300,
            nbpane = 20,
            ind_gr_box = FALSE,
            var_gr_box = FALSE,
            cor_tab_box_max = FALSE,
            cor_tab_box_min = FALSE,
            abs = 1,
            ord = 2,
            cex = 1,
            name_box = FALSE,
            scale_unit_box = TRUE,
            center_pane_box = TRUE,
            scale_pane_box = FALSE,
            level_search = 0.2, ...) {

            super$initialize(
                package='SEDA',
                name='QDABOOT',
                requiresData=TRUE,
                ...)

            private$..prod <- jmvcore::OptionVariable$new(
                "prod",
                prod,
                suggested=list(
                    "nominal"))
            private$..pane <- jmvcore::OptionVariable$new(
                "pane",
                pane,
                suggested=list(
                    "nominal"))
            private$..senso <- jmvcore::OptionVariables$new(
                "senso",
                senso,
                suggested=list(
                    "continuous"))
            private$..thresh <- jmvcore::OptionNumber$new(
                "thresh",
                thresh,
                default=0.05,
                min=0,
                max=1)
            private$..nbsimul <- jmvcore::OptionNumber$new(
                "nbsimul",
                nbsimul,
                default=300,
                min=10,
                max=1000)
            private$..nbpane <- jmvcore::OptionNumber$new(
                "nbpane",
                nbpane,
                default=20,
                min=2)
            private$..ind_gr_box <- jmvcore::OptionBool$new(
                "ind_gr_box",
                ind_gr_box,
                default=FALSE)
            private$..var_gr_box <- jmvcore::OptionBool$new(
                "var_gr_box",
                var_gr_box,
                default=FALSE)
            private$..cor_tab_box_max <- jmvcore::OptionBool$new(
                "cor_tab_box_max",
                cor_tab_box_max,
                default=FALSE)
            private$..cor_tab_box_min <- jmvcore::OptionBool$new(
                "cor_tab_box_min",
                cor_tab_box_min,
                default=FALSE)
            private$..abs <- jmvcore::OptionInteger$new(
                "abs",
                abs,
                default=1)
            private$..ord <- jmvcore::OptionInteger$new(
                "ord",
                ord,
                default=2)
            private$..cex <- jmvcore::OptionNumber$new(
                "cex",
                cex,
                default=1,
                min=0.1,
                max=2)
            private$..name_box <- jmvcore::OptionBool$new(
                "name_box",
                name_box,
                default=FALSE)
            private$..scale_unit_box <- jmvcore::OptionBool$new(
                "scale_unit_box",
                scale_unit_box,
                default=TRUE)
            private$..center_pane_box <- jmvcore::OptionBool$new(
                "center_pane_box",
                center_pane_box,
                default=TRUE)
            private$..scale_pane_box <- jmvcore::OptionBool$new(
                "scale_pane_box",
                scale_pane_box,
                default=FALSE)
            private$..level_search <- jmvcore::OptionNumber$new(
                "level_search",
                level_search,
                default=0.2,
                min=0.01,
                max=1)

            self$.addOption(private$..prod)
            self$.addOption(private$..pane)
            self$.addOption(private$..senso)
            self$.addOption(private$..thresh)
            self$.addOption(private$..nbsimul)
            self$.addOption(private$..nbpane)
            self$.addOption(private$..ind_gr_box)
            self$.addOption(private$..var_gr_box)
            self$.addOption(private$..cor_tab_box_max)
            self$.addOption(private$..cor_tab_box_min)
            self$.addOption(private$..abs)
            self$.addOption(private$..ord)
            self$.addOption(private$..cex)
            self$.addOption(private$..name_box)
            self$.addOption(private$..scale_unit_box)
            self$.addOption(private$..center_pane_box)
            self$.addOption(private$..scale_pane_box)
            self$.addOption(private$..level_search)
        }),
    active = list(
        prod = function() private$..prod$value,
        pane = function() private$..pane$value,
        senso = function() private$..senso$value,
        thresh = function() private$..thresh$value,
        nbsimul = function() private$..nbsimul$value,
        nbpane = function() private$..nbpane$value,
        ind_gr_box = function() private$..ind_gr_box$value,
        var_gr_box = function() private$..var_gr_box$value,
        cor_tab_box_max = function() private$..cor_tab_box_max$value,
        cor_tab_box_min = function() private$..cor_tab_box_min$value,
        abs = function() private$..abs$value,
        ord = function() private$..ord$value,
        cex = function() private$..cex$value,
        name_box = function() private$..name_box$value,
        scale_unit_box = function() private$..scale_unit_box$value,
        center_pane_box = function() private$..center_pane_box$value,
        scale_pane_box = function() private$..scale_pane_box$value,
        level_search = function() private$..level_search$value),
    private = list(
        ..prod = NA,
        ..pane = NA,
        ..senso = NA,
        ..thresh = NA,
        ..nbsimul = NA,
        ..nbpane = NA,
        ..ind_gr_box = NA,
        ..var_gr_box = NA,
        ..cor_tab_box_max = NA,
        ..cor_tab_box_min = NA,
        ..abs = NA,
        ..ord = NA,
        ..cex = NA,
        ..name_box = NA,
        ..scale_unit_box = NA,
        ..center_pane_box = NA,
        ..scale_pane_box = NA,
        ..level_search = NA)
)

QDABOOTResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plotspa = function() private$.items[["plotspa"]],
        plotvaria = function() private$.items[["plotvaria"]],
        plotpane = function() private$.items[["plotpane"]],
        plotvar = function() private$.items[["plotvar"]],
        plotind = function() private$.items[["plotind"]],
        eigenGr = function() private$.items[["eigenGr"]],
        hotGr = function() private$.items[["hotGr"]],
        corGr = function() private$.items[["corGr"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of QDA data with resampling")
            self$add(jmvcore::Image$new(
                options=options,
                name="plotspa",
                title="Representation of the products with confidence ellipses",
                width=900,
                height=600,
                renderFun=".plotSpace"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvaria",
                visible="(var_gr_box)",
                title="Variability of the sensory attributes",
                width=600,
                height=600,
                renderFun=".plotvariavar"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotpane",
                visible="(ind_gr_box)",
                title="Individual variability around products",
                width=900,
                height=600,
                renderFun=".plotPane"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar",
                title="Representation of the sensory attributes",
                width=600,
                height=600,
                renderFun=".plotVaraxe"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotind",
                title="Representation of the products",
                width=900,
                height=600,
                renderFun=".plotIndaxe"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eigen_table = function() private$.items[["eigen_table"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="eigenGr",
                            title="Eigenvalue decomposition")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eigen_table",
                            title="",
                            columns=list(
                                list(
                                    `name`="facto", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="eig", 
                                    `title`="Eigenvalue", 
                                    `type`="number"),
                                list(
                                    `name`="eig_pct", 
                                    `title`="% of variance", 
                                    `type`="number"),
                                list(
                                    `name`="eig_pct_cum", 
                                    `title`="Cumulative %", 
                                    `type`="number"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    hot_table = function() private$.items[["hot_table"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="hotGr",
                            title="Hotelling test")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="hot_table",
                            title="",
                            columns=list()))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    cor_tab_moy = function() private$.items[["cor_tab_moy"]],
                    cor_tab_max = function() private$.items[["cor_tab_max"]],
                    cor_tab_min = function() private$.items[["cor_tab_min"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="corGr",
                            title="Correlation table(s)")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="cor_tab_moy",
                            title="Mean correlation",
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="cor_tab_max",
                            title="Maximum correlation",
                            visible="(cor_tab_box_max)",
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="cor_tab_min",
                            title="Minmum correlation",
                            visible="(cor_tab_box_min)",
                            columns=list()))}))$new(options=options))}))

QDABOOTBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "QDABOOTBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'SEDA',
                name = 'QDABOOT',
                version = c(1,0,0),
                options = options,
                results = QDABOOTResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Analysis of QDA data with resampling
#'
#' 
#' @param data .
#' @param prod .
#' @param pane .
#' @param senso .
#' @param thresh .
#' @param nbsimul .
#' @param nbpane .
#' @param ind_gr_box .
#' @param var_gr_box .
#' @param cor_tab_box_max .
#' @param cor_tab_box_min .
#' @param abs .
#' @param ord .
#' @param cex .
#' @param name_box .
#' @param scale_unit_box .
#' @param center_pane_box .
#' @param scale_pane_box .
#' @param level_search .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plotspa} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvaria} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotpane} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotind} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$eigenGr$eigen_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$hotGr$hot_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$corGr$cor_tab_moy} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$corGr$cor_tab_max} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$corGr$cor_tab_min} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
QDABOOT <- function(
    data,
    prod,
    pane,
    senso,
    thresh = 0.05,
    nbsimul = 300,
    nbpane = 20,
    ind_gr_box = FALSE,
    var_gr_box = FALSE,
    cor_tab_box_max = FALSE,
    cor_tab_box_min = FALSE,
    abs = 1,
    ord = 2,
    cex = 1,
    name_box = FALSE,
    scale_unit_box = TRUE,
    center_pane_box = TRUE,
    scale_pane_box = FALSE,
    level_search = 0.2) {

    if ( ! requireNamespace('jmvcore'))
        stop('QDABOOT requires jmvcore to be installed (restart may be required)')

    if ( ! missing(prod)) prod <- jmvcore::resolveQuo(jmvcore::enquo(prod))
    if ( ! missing(pane)) pane <- jmvcore::resolveQuo(jmvcore::enquo(pane))
    if ( ! missing(senso)) senso <- jmvcore::resolveQuo(jmvcore::enquo(senso))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(prod), prod, NULL),
            `if`( ! missing(pane), pane, NULL),
            `if`( ! missing(senso), senso, NULL))


    options <- QDABOOTOptions$new(
        prod = prod,
        pane = pane,
        senso = senso,
        thresh = thresh,
        nbsimul = nbsimul,
        nbpane = nbpane,
        ind_gr_box = ind_gr_box,
        var_gr_box = var_gr_box,
        cor_tab_box_max = cor_tab_box_max,
        cor_tab_box_min = cor_tab_box_min,
        abs = abs,
        ord = ord,
        cex = cex,
        name_box = name_box,
        scale_unit_box = scale_unit_box,
        center_pane_box = center_pane_box,
        scale_pane_box = scale_pane_box,
        level_search = level_search)

    analysis <- QDABOOTClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
