
# This file is automatically generated, you probably don't want to edit this

SortingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SortingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            actvars = NULL,
            individus = NULL,
            qualisup = NULL,
            tuto = TRUE,
            showCode = FALSE,
            nFactors = 2,
            abs = 1,
            ord = 2,
            varmodqualisup = TRUE,
            varmodvar = TRUE,
            proba = 5,
            indcoord = FALSE,
            indcontrib = FALSE,
            indcos = FALSE,
            varcoord = FALSE,
            varcontrib = FALSE,
            varcos = FALSE,
            ventil = 5,
            modality = "cos2 10",
            leveltext = 5,
            longformat = FALSE,
            ncp = 5,
            graphclassif = FALSE,
            nbclust = -1, ...) {

            super$initialize(
                package="SEDA",
                name="Sorting",
                requiresData=TRUE,
                ...)

            private$..actvars <- jmvcore::OptionVariables$new(
                "actvars",
                actvars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..individus <- jmvcore::OptionVariable$new(
                "individus",
                individus,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..qualisup <- jmvcore::OptionVariables$new(
                "qualisup",
                qualisup,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..tuto <- jmvcore::OptionBool$new(
                "tuto",
                tuto,
                default=TRUE)
            private$..showCode <- jmvcore::OptionBool$new(
                "showCode",
                showCode,
                default=FALSE)
            private$..nFactors <- jmvcore::OptionInteger$new(
                "nFactors",
                nFactors,
                default=2)
            private$..abs <- jmvcore::OptionInteger$new(
                "abs",
                abs,
                default=1)
            private$..ord <- jmvcore::OptionInteger$new(
                "ord",
                ord,
                default=2)
            private$..varmodqualisup <- jmvcore::OptionBool$new(
                "varmodqualisup",
                varmodqualisup,
                default=TRUE)
            private$..varmodvar <- jmvcore::OptionBool$new(
                "varmodvar",
                varmodvar,
                default=TRUE)
            private$..proba <- jmvcore::OptionNumber$new(
                "proba",
                proba,
                default=5)
            private$..indcoord <- jmvcore::OptionBool$new(
                "indcoord",
                indcoord,
                default=FALSE)
            private$..indcontrib <- jmvcore::OptionBool$new(
                "indcontrib",
                indcontrib,
                default=FALSE)
            private$..indcos <- jmvcore::OptionBool$new(
                "indcos",
                indcos,
                default=FALSE)
            private$..varcoord <- jmvcore::OptionBool$new(
                "varcoord",
                varcoord,
                default=FALSE)
            private$..varcontrib <- jmvcore::OptionBool$new(
                "varcontrib",
                varcontrib,
                default=FALSE)
            private$..varcos <- jmvcore::OptionBool$new(
                "varcos",
                varcos,
                default=FALSE)
            private$..ventil <- jmvcore::OptionNumber$new(
                "ventil",
                ventil,
                default=5)
            private$..modality <- jmvcore::OptionString$new(
                "modality",
                modality,
                default="cos2 10")
            private$..leveltext <- jmvcore::OptionNumber$new(
                "leveltext",
                leveltext,
                default=5)
            private$..longformat <- jmvcore::OptionBool$new(
                "longformat",
                longformat,
                default=FALSE)
            private$..ncp <- jmvcore::OptionInteger$new(
                "ncp",
                ncp,
                default=5)
            private$..graphclassif <- jmvcore::OptionBool$new(
                "graphclassif",
                graphclassif,
                default=FALSE)
            private$..newvar <- jmvcore::OptionOutput$new(
                "newvar")
            private$..nbclust <- jmvcore::OptionInteger$new(
                "nbclust",
                nbclust,
                default=-1)
            private$..newvar2 <- jmvcore::OptionOutput$new(
                "newvar2")

            self$.addOption(private$..actvars)
            self$.addOption(private$..individus)
            self$.addOption(private$..qualisup)
            self$.addOption(private$..tuto)
            self$.addOption(private$..showCode)
            self$.addOption(private$..nFactors)
            self$.addOption(private$..abs)
            self$.addOption(private$..ord)
            self$.addOption(private$..varmodqualisup)
            self$.addOption(private$..varmodvar)
            self$.addOption(private$..proba)
            self$.addOption(private$..indcoord)
            self$.addOption(private$..indcontrib)
            self$.addOption(private$..indcos)
            self$.addOption(private$..varcoord)
            self$.addOption(private$..varcontrib)
            self$.addOption(private$..varcos)
            self$.addOption(private$..ventil)
            self$.addOption(private$..modality)
            self$.addOption(private$..leveltext)
            self$.addOption(private$..longformat)
            self$.addOption(private$..ncp)
            self$.addOption(private$..graphclassif)
            self$.addOption(private$..newvar)
            self$.addOption(private$..nbclust)
            self$.addOption(private$..newvar2)
        }),
    active = list(
        actvars = function() private$..actvars$value,
        individus = function() private$..individus$value,
        qualisup = function() private$..qualisup$value,
        tuto = function() private$..tuto$value,
        showCode = function() private$..showCode$value,
        nFactors = function() private$..nFactors$value,
        abs = function() private$..abs$value,
        ord = function() private$..ord$value,
        varmodqualisup = function() private$..varmodqualisup$value,
        varmodvar = function() private$..varmodvar$value,
        proba = function() private$..proba$value,
        indcoord = function() private$..indcoord$value,
        indcontrib = function() private$..indcontrib$value,
        indcos = function() private$..indcos$value,
        varcoord = function() private$..varcoord$value,
        varcontrib = function() private$..varcontrib$value,
        varcos = function() private$..varcos$value,
        ventil = function() private$..ventil$value,
        modality = function() private$..modality$value,
        leveltext = function() private$..leveltext$value,
        longformat = function() private$..longformat$value,
        ncp = function() private$..ncp$value,
        graphclassif = function() private$..graphclassif$value,
        newvar = function() private$..newvar$value,
        nbclust = function() private$..nbclust$value,
        newvar2 = function() private$..newvar2$value),
    private = list(
        ..actvars = NA,
        ..individus = NA,
        ..qualisup = NA,
        ..tuto = NA,
        ..showCode = NA,
        ..nFactors = NA,
        ..abs = NA,
        ..ord = NA,
        ..varmodqualisup = NA,
        ..varmodvar = NA,
        ..proba = NA,
        ..indcoord = NA,
        ..indcontrib = NA,
        ..indcos = NA,
        ..varcoord = NA,
        ..varcontrib = NA,
        ..varcos = NA,
        ..ventil = NA,
        ..modality = NA,
        ..leveltext = NA,
        ..longformat = NA,
        ..ncp = NA,
        ..graphclassif = NA,
        ..newvar = NA,
        ..nbclust = NA,
        ..newvar2 = NA)
)

SortingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SortingResults",
    inherit = jmvcore::Group,
    active = list(
        mcaCache = function() private$.items[["mcaCache"]],
        classifCache = function() private$.items[["classifCache"]],
        instructions = function() private$.items[["instructions"]],
        step1Guide = function() private$.items[["step1Guide"]],
        dfresgroup = function() private$.items[["dfresgroup"]],
        longformatdata = function() private$.items[["longformatdata"]],
        step2Guide = function() private$.items[["step2Guide"]],
        eigengroup = function() private$.items[["eigengroup"]],
        plotindiv = function() private$.items[["plotindiv"]],
        plotvar = function() private$.items[["plotvar"]],
        plotitemvar = function() private$.items[["plotitemvar"]],
        dimdesc = function() private$.items[["dimdesc"]],
        individus = function() private$.items[["individus"]],
        variables = function() private$.items[["variables"]],
        step3Guide = function() private$.items[["step3Guide"]],
        plotclassif = function() private$.items[["plotclassif"]],
        newvar = function() private$.items[["newvar"]],
        newvar2 = function() private$.items[["newvar2"]],
        code = function() private$.items[["code"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of Sorting Data",
                refs=list(
                    "sorting",
                    "sensominer",
                    "senso"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mcaCache",
                title="MCA cache",
                visible=FALSE,
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ventil",
                    "ncp",
                    "nFactors",
                    "abs",
                    "ord")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="classifCache",
                title="Classification cache",
                visible=FALSE,
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ventil",
                    "ncp",
                    "nbclust")))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible="(tuto)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="step1Guide",
                title=""))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    dfres = function() private$.items[["dfres"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="dfresgroup",
                            title="Description of the Stimuli from Sorting Labels")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="dfres",
                            title="Words Associated with the Stimuli",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "individus",
                                "leveltext"),
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="Stimulus", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="word", 
                                    `title`="Word", 
                                    `type`="text"),
                                list(
                                    `name`="internper", 
                                    `title`="Internal %", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="globper", 
                                    `title`="Global %", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="internfreq", 
                                    `title`="Internal frequency", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="globfreq", 
                                    `title`="Global frequency", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="pvaluedfres", 
                                    `title`="p", 
                                    `type`="Number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="vtest", 
                                    `title`="V-test", 
                                    `type`="Number", 
                                    `format`="zto"))))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="longformatdata",
                title="Long-Format Sorting Labels",
                visible="(longformat)",
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "longformat")))
            self$add(jmvcore::Html$new(
                options=options,
                name="step2Guide",
                title=""))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eigen = function() private$.items[["eigen"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="eigengroup",
                            title="Eigenvalue Decomposition")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eigen",
                            title="Eigenvalue and (Cumulative) Percentage of Variance",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "ventil",
                                "ncp",
                                "nFactors",
                                "abs",
                                "ord"),
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="eigenvalue", 
                                    `title`="Eigenvalue", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="purcent", 
                                    `title`="% of the variance", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="purcentcum", 
                                    `title`="Cumulative %", 
                                    `type`="Number", 
                                    `format`="zto"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotindiv",
                title="Representation of the Stimuli",
                width=800,
                height=600,
                renderFun=".plotindiv",
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ventil",
                    "ncp",
                    "nFactors",
                    "abs",
                    "ord")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar",
                title="Representation of the Subjects",
                width=800,
                height=600,
                renderFun=".plotvar",
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ventil",
                    "ncp",
                    "nFactors",
                    "abs",
                    "ord")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotitemvar",
                title="Representation of the Sorting Categories",
                width=800,
                height=600,
                renderFun=".plotitemvar",
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ventil",
                    "ncp",
                    "nFactors",
                    "abs",
                    "ord",
                    "varmodqualisup",
                    "varmodvar",
                    "modality")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    categorical = function() private$.items[["categorical"]],
                    categories = function() private$.items[["categories"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="dimdesc",
                            title="Automatic Description of the Dimensions")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="categorical",
                            title="Subjects Associated with the Dimensions",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "individus",
                                "ventil",
                                "nFactors",
                                "proba"),
                            columns=list(
                                list(
                                    `name`="dimension", 
                                    `title`="Dimension", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="variable", 
                                    `title`="Subject", 
                                    `type`="text"),
                                list(
                                    `name`="r2", 
                                    `title`="R\u00B2", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="Number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="categories",
                            title="Sorting Categories Associated with the Dimensions",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "individus",
                                "ventil",
                                "nFactors",
                                "proba"),
                            columns=list(
                                list(
                                    `name`="dimension", 
                                    `title`="Dimension", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="category", 
                                    `title`="Category", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="Estimate", 
                                    `type`="Number", 
                                    `format`="zto"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="Number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    coordonnees = function() private$.items[["coordonnees"]],
                    contribution = function() private$.items[["contribution"]],
                    cosinus = function() private$.items[["cosinus"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="individus",
                            title="Stimulus Tables")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coordonnees",
                            title="Coordinates Table",
                            visible="(indcoord)",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "individus",
                                "ventil",
                                "nFactors",
                                "ncp"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="contribution",
                            title="Contributions Table",
                            visible="(indcontrib)",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "individus",
                                "ventil",
                                "nFactors",
                                "ncp"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="cosinus",
                            title="Cosine Table",
                            visible="(indcos)",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "individus",
                                "ventil",
                                "nFactors",
                                "ncp"),
                            columns=list()))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    coordonnees = function() private$.items[["coordonnees"]],
                    contribution = function() private$.items[["contribution"]],
                    cosinus = function() private$.items[["cosinus"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="variables",
                            title="Subject Tables")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coordonnees",
                            title="Coordinates Table",
                            visible="(varcoord)",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "ventil",
                                "nFactors",
                                "ncp"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="contribution",
                            title="Contributions Table",
                            visible="(varcontrib)",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "ventil",
                                "nFactors",
                                "ncp"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="cosinus",
                            title="Cosine Table",
                            visible="(varcos)",
                            clearWith=list(
                                "actvars",
                                "qualisup",
                                "ventil",
                                "nFactors",
                                "ncp"),
                            columns=list()))}))$new(options=options))
            self$add(jmvcore::Html$new(
                options=options,
                name="step3Guide",
                title="",
                visible="(graphclassif)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotclassif",
                title="Representation of the Stimuli According to Clusters",
                visible="(graphclassif)",
                width=800,
                height=600,
                renderFun=".plotclassif",
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ventil",
                    "ncp",
                    "nbclust",
                    "abs",
                    "ord")))
            self$add(jmvcore::Output$new(
                options=options,
                name="newvar",
                title="Coordinates",
                measureType="continuous",
                initInRun=TRUE,
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ventil",
                    "ncp")))
            self$add(jmvcore::Output$new(
                options=options,
                name="newvar2",
                title="Cluster",
                measureType="nominal",
                initInRun=TRUE,
                clearWith=list(
                    "actvars",
                    "qualisup",
                    "individus",
                    "ventil",
                    "ncp",
                    "nbclust")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="code",
                title="R Code",
                visible="(showCode)",
                clearWith=list(
                    "showCode",
                    "actvars",
                    "qualisup",
                    "individus",
                    "ventil",
                    "leveltext",
                    "abs",
                    "ord",
                    "varmodqualisup",
                    "varmodvar",
                    "modality",
                    "nFactors",
                    "proba",
                    "indcoord",
                    "indcontrib",
                    "indcos",
                    "varcoord",
                    "varcontrib",
                    "varcos",
                    "ncp",
                    "graphclassif",
                    "nbclust")))}))

SortingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SortingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "Sorting",
                version = c(1,1,0),
                options = options,
                results = SortingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Analysis of Sorting Data
#'
#' 
#' @param data .
#' @param actvars .
#' @param individus .
#' @param qualisup .
#' @param tuto .
#' @param showCode .
#' @param nFactors .
#' @param abs .
#' @param ord .
#' @param varmodqualisup .
#' @param varmodvar .
#' @param proba .
#' @param indcoord .
#' @param indcontrib .
#' @param indcos .
#' @param varcoord .
#' @param varcontrib .
#' @param varcos .
#' @param ventil .
#' @param modality .
#' @param leveltext .
#' @param longformat .
#' @param ncp .
#' @param graphclassif .
#' @param nbclust .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$mcaCache} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$classifCache} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$step1Guide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dfresgroup$dfres} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$longformatdata} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$step2Guide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$eigengroup$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotindiv} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotitemvar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$dimdesc$categorical} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dimdesc$categories} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$individus$coordonnees} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$individus$contribution} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$individus$cosinus} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variables$coordonnees} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variables$contribution} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variables$cosinus} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$step3Guide} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotclassif} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$newvar} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$newvar2} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$code} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
Sorting <- function(
    data,
    actvars,
    individus,
    qualisup,
    tuto = TRUE,
    showCode = FALSE,
    nFactors = 2,
    abs = 1,
    ord = 2,
    varmodqualisup = TRUE,
    varmodvar = TRUE,
    proba = 5,
    indcoord = FALSE,
    indcontrib = FALSE,
    indcos = FALSE,
    varcoord = FALSE,
    varcontrib = FALSE,
    varcos = FALSE,
    ventil = 5,
    modality = "cos2 10",
    leveltext = 5,
    longformat = FALSE,
    ncp = 5,
    graphclassif = FALSE,
    nbclust = -1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Sorting requires jmvcore to be installed (restart may be required)")

    if ( ! missing(actvars)) actvars <- jmvcore::resolveQuo(jmvcore::enquo(actvars))
    if ( ! missing(individus)) individus <- jmvcore::resolveQuo(jmvcore::enquo(individus))
    if ( ! missing(qualisup)) qualisup <- jmvcore::resolveQuo(jmvcore::enquo(qualisup))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(actvars), actvars, NULL),
            `if`( ! missing(individus), individus, NULL),
            `if`( ! missing(qualisup), qualisup, NULL))

    for (v in actvars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in individus) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in qualisup) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- SortingOptions$new(
        actvars = actvars,
        individus = individus,
        qualisup = qualisup,
        tuto = tuto,
        showCode = showCode,
        nFactors = nFactors,
        abs = abs,
        ord = ord,
        varmodqualisup = varmodqualisup,
        varmodvar = varmodvar,
        proba = proba,
        indcoord = indcoord,
        indcontrib = indcontrib,
        indcos = indcos,
        varcoord = varcoord,
        varcontrib = varcontrib,
        varcos = varcos,
        ventil = ventil,
        modality = modality,
        leveltext = leveltext,
        longformat = longformat,
        ncp = ncp,
        graphclassif = graphclassif,
        nbclust = nbclust)

    analysis <- SortingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

